import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const VEC = process.env.VEC_DIR || join(__dir, '..', '.tests-cache', 'vectors');

const manifest = JSON.parse(readFileSync(join(VEC, 'manifest.json'), 'utf-8'));
const models = manifest.testModels;
const scalars = manifest.scalars;

function getReadMethod(type) {
  const map = {
    'int32': 'readInt32',
    'int64': 'readInt64',
    'uint32': 'readUint32',
    'uint64': 'readUint64',
    'float32': 'readFloat32',
    'float64': 'readFloat64',
    'string': 'readString',
    'bytes': 'readBytes',
    'bool': 'readBool',
  };
  return map[type] || 'readInt32';
}

function getWriteMethod(type) {
  const map = {
    'int32': 'writeInt32',
    'int64': 'writeInt64',
    'uint32': 'writeUint32',
    'uint64': 'writeUint64',
    'float32': 'writeFloat32',
    'float64': 'writeFloat64',
    'string': 'writeString',
    'bytes': 'writeBytes',
    'bool': 'writeBool',
  };
  return map[type] || 'writeInt32';
}

function toCamelCase(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

let scalarCode = '';
for (const [name, info] of Object.entries(scalars)) {
  scalarCode += `
  // ${name}
  final mpData${name} = File(p.join(VEC, 'scalars', '${name}.mp')).readAsBytesSync();
  final r${name} = MsgPackReader(mpData${name});
  final val${name} = r${name}.${getReadMethod(info.type)}();
  final w${name} = MsgPackWriter();
  w${name}.${getWriteMethod(info.type)}(val${name});
  File(p.join(OUT, 'scalars', '${name}.mp')).writeAsBytesSync(w${name}.toBytes());
  passed++;
`;
}

let modelCode = '';
for (const model of models) {
  const camel = toCamelCase(model);
  modelCode += `
  // ${model}
  final codec${model} = getCodec('${model}');
  // msgpack
  final mpData${model} = File(p.join(VEC, '${model}.msgpack')).readAsBytesSync();
  final r${model} = MsgPackReader(mpData${model});
  final obj${model} = codec${model}.decode(r${model});
  final w${model} = MsgPackWriter();
  codec${model}.encode(w${model}, obj${model});
  File(p.join(OUT, '${model}.msgpack')).writeAsBytesSync(w${model}.toBytes());
  passed++;
  // json
  final jsonData${model} = File(p.join(VEC, '${model}.json')).readAsBytesSync();
  final rj${model} = JsonReader(jsonData${model});
  final objj${model} = codec${model}.decode(rj${model});
  final wj${model} = JsonWriter();
  codec${model}.encode(wj${model}, objj${model});
  File(p.join(OUT, '${model}.json')).writeAsBytesSync(wj${model}.toBytes());
  passed++;
  // unformatted json
  final ufData${model} = File(p.join(VEC, '${model}.unformatted.json')).readAsBytesSync();
  final ru${model} = JsonReader(ufData${model});
  final obju${model} = codec${model}.decode(ru${model});
  final wu${model} = JsonWriter();
  codec${model}.encode(wu${model}, obju${model});
  File(p.join(OUT, '${model}.unformatted.json')).writeAsBytesSync(wu${model}.toBytes());
  passed++;
  // gron
  final gronData${model} = File(p.join(VEC, '${model}.gron')).readAsBytesSync();
  final rg${model} = GronReader(gronData${model});
  final objg${model} = codec${model}.decode(rg${model});
  final wg${model} = GronWriter();
  codec${model}.encode(wg${model}, objg${model});
  File(p.join(OUT, '${model}.gron')).writeAsBytesSync(wg${model}.toBytes());
  passed++;
`;
}

let codecSwitch = '';
for (const model of models) {
  codecSwitch += `      case '${model}': return ${model}Codec;\n`;
}

const code = `// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io';
import 'dart:typed_data';
import 'package:path/path.dart' as p;
import 'package:specodec/specodec.dart';
import 'emit_gen/specodec_all_types.dart';

void main() {
  final VEC = Platform.environment['VEC_DIR']!;
  final OUT = Platform.environment['OUT_DIR']!;
  Directory(OUT).createSync(recursive: true);
  Directory(p.join(OUT, 'scalars')).createSync(recursive: true);

  var passed = 0;
  var failed = 0;

  // Scalar tests
${scalarCode}

  // Object tests
${modelCode}

  print('emit-dart: \$passed passed, \$failed failed');
  if (failed > 0) exit(1);
}

SpecCodec<dynamic> getCodec(String name) {
  switch (name) {
${codecSwitch}    default: throw Exception('Unknown codec: \$name');
  }
}
`;

writeFileSync(join(__dir, 'run_emit.dart'), code);
console.log(`Generated run_emit.dart with ${models.length} models + ${Object.keys(scalars).length} scalars`);