// Generated by generate_emit_runner.mjs. DO NOT EDIT.
import 'dart:io' show File, Directory, Platform, exit;
import 'package:specodec/specodec.dart';
import '../emit_gen/specodec_all_types/all_types.dart';

import 'test_models.dart';
import 'test_nested.dart';
import 'test_nested_deep.dart';

void main() {
  final vec = Platform.environment['VEC_DIR']!;
  final out = Platform.environment['OUT_DIR']!;
  Directory(out).createSync(recursive: true);
  Directory('$out/scalars').createSync(recursive: true);

  int passed = 0, failed = 0;

  final (prunModels, frunModels) = runModels(vec, out); passed += prunModels; failed += frunModels;
  final (prunNested, frunNested) = runNested(vec, out); passed += prunNested; failed += frunNested;
  final (prunNestedDeep, frunNestedDeep) = runNestedDeep(vec, out); passed += prunNestedDeep; failed += frunNestedDeep;

  print('emit-dart: $passed passed, $failed failed');
  if (failed > 0) exit(1);
}
