FROM dhi.io/dart:3-alpine3.22-dev AS runner
WORKDIR /app
ARG HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
ENV http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY} HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} ALL_PROXY=${ALL_PROXY}

COPY --from=emit_dart_src pubspec.yaml ./
COPY --from=specodec-runtime-dart . /specodec-dart/
RUN mkdir -p lib
COPY --from=emit_gen test_service_types.dart lib/
RUN --mount=type=cache,target=/root/.pub-cache \
    dart pub get
COPY --from=emit_dart_src bin/run_emit.dart bin/
COPY --from=emit_dart_src bin/dump_emit.dart bin/

COPY vectors/ /app/vectors/
RUN mkdir -p /app/output_emit_dart
ENV VEC_DIR=/app/vectors OUT_DIR=/app/output_emit_dart
RUN dart run bin/run_emit.dart
