FROM dhi.io/dart:3-alpine3.22-dev AS runner
WORKDIR /app
ARG HTTP_PROXY HTTPS_PROXY http_proxy https_proxy ALL_PROXY all_proxy
ENV http_proxy=${HTTP_PROXY} https_proxy=${HTTPS_PROXY} HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTPS_PROXY} ALL_PROXY=${ALL_PROXY}
COPY --from=run pubspec.yaml ./
COPY --from=specodec-runtime-dart . /specodec-dart/
COPY --from=run bin/ bin/
COPY --from=vectors . /app/vectors/
COPY --from=output_ts . /app/output_ts/
RUN mkdir -p /app/output_dart/scalars
RUN --mount=type=cache,target=/root/.pub-cache \
    dart pub get && \
    dart compile exe bin/run_dart.dart -o /app/run_dart_bin
ENV VEC_DIR=/app/vectors OUT_DIR=/app/output_dart
RUN /app/run_dart_bin